[package]
name = "enishi-exec"
version = "0.1.0"
edition = "2021"

[dependencies]
enishi-core = { path = "../enishi-core" }
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
bloom = "0.3"
statrs = "0.16"
