replicaCount: 2

image:
  repository: ghcr.io/your-org/fcdb
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: fcdb.local
      paths:
        - path: /
          pathType: Prefix

metrics:
  port: 9090

env:
  RUST_LOG: "info"
  FCDB_STORAGE_PATH: "/app/data"
