[package]
name = "fcdb-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
blake3 = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
integer-encoding = "3.0"