apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enishi.fullname" . }}
  labels:
    app: {{ include "enishi.name" . }}
    chart: {{ include "enishi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "enishi.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "enishi.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: enishi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: {{ .Values.metrics.port }}
          env:
            - name: RUST_LOG
              value: "{{ .Values.env.RUST_LOG }}"
            - name: ENISHI_STORAGE_PATH
              value: "{{ .Values.env.ENISHI_STORAGE_PATH }}"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          emptyDir: {}
